import assert from "node:assert/strict";
import fs from "node:fs";
import {atlasZoomTransform} from "../src/atlas-marker-groups.js";
const root=new URL("../",import.meta.url);
const sources=JSON.parse(fs.readFileSync(new URL("data/sources.json",root),"utf8"));
const h=sources.find(s=>s.id==="taiwan-heping-island-live");
assert.ok(h,"Heping source must remain in the registry for revalidation");
assert.equal(h.truth,"LIVE_VIDEO");
assert.equal(h.permission,"EMBED_ALLOWED");
assert.equal(h.health,"DEGRADED");
assert.equal(h.watchHold,true);
assert.equal(h.featuredHold,true);
assert.match(h.failureReason,/VISITOR_PLAYBACK_REJECTED.*Video unavailable/);
assert.ok(h.playbackVerifiedAt,"Historic proof must not be erased");
const fit=atlasZoomTransform({scale:1,x:0,y:0},2,.5,.5,1000,500);
assert.deepEqual(fit,{scale:2,x:-500,y:-250});
assert.deepEqual(atlasZoomTransform(fit,1,.5,.5,1000,500),{scale:1,x:0,y:0});
const max=atlasZoomTransform({scale:1,x:0,y:0},50,1,1,1000,500);
assert.equal(max.scale,5);
assert.equal(max.x,-4000);assert.equal(max.y,-2000);
assert.deepEqual(atlasZoomTransform({scale:1,x:0,y:0},.1,.5,.5,1000,500),{scale:1,x:0,y:0});
const source=fs.readFileSync(new URL("src/atlas-marker-groups.js",root),"utf8");
const app=fs.readFileSync(new URL("src/app-lite.js",root),"utf8");
for(const phrase of ["aria-label\",\"Zoom in","aria-label\",\"Zoom out","Reset to world view","pointerdown","pointermove","pointerup","atlasWorld.style.transform","atlasView.scale)/42","atlasView.scale)/42","passive:false","renderAtlasMarkerGroups(a,markers,repaint)"])assert.ok(source.includes(phrase),phrase);
assert.ok(app.includes("ERNAtlasGroups(a,markers,renderMap)"),"Map rerender must follow zoom and preserve category selection");
assert.ok(source.includes("if(group.length===1){world.append(group[0].node)"),"Single places stay actionable");
assert.ok(source.includes("world.append(pin)"),"Grouped pins must zoom with geography");
assert.ok(source.includes("entry.node.click()"),"Cluster navigation still retains original source action");
assert.ok(source.includes("a.append(panel)"),"Group drawer must not scale with map");
assert.ok(source.includes('url(\\\"/assets/world-map-natural-earth.svg\\\")')||source.includes("world-map-natural-earth.svg"),"Actual geography remains the map base");
console.log("Atlas zoom/pan and screenshot-reported broken-camera hold pass");
