import assert from "node:assert/strict";
import fs from "node:fs";
const app=fs.readFileSync(new URL("../src/app-lite.js",import.meta.url),"utf8");
assert.ok(app.includes('function atlasReferenceEligible(s){return atlasBaseEligible(s)&&s.health==="HEALTHY"&&!currentTruthClaim(s)&&Boolean(referenceHandoffUrl(s))}'),"reference-only Atlas entries must require healthy catalog state plus a valid handoff");
assert.ok(app.includes('function atlasEligible(s){return atlasBaseEligible(s)&&(currentTruthClaim(s)||atlasReferenceEligible(s))}'),"Atlas must exclude stale places that have no usable current/reference handoff");
assert.ok(app.includes('p.className="map-pin"+(inside?"":" external")+(reference?" reference":"")'),"reference-only Atlas pins must be visually distinct");
assert.ok(app.includes('Reference only · official source available'),"reference-only Atlas pins must be labeled explicitly");
assert.ok(app.includes('h.textContent="Live view temporarily unavailable"'),"recheck viewer must explain temporary live-view unavailability");
assert.ok(app.includes('a.textContent="Open official source"'),"recheck viewer must provide a prominent official-source recovery action");
assert.ok(app.includes('ERN is not treating this source as current right now.'),"reference handoff must preserve conservative source truth");
assert.ok(app.includes('openViewer(alt,{record:current,updateHash:current})'),"non-current alternates must not record interest or create stale deep links");
assert.ok(app.includes('p.onclick=()=>openViewer(s,{record:current,updateHash:current})'),"Atlas reference pins must not record interest or create stale deep links");
assert.ok(app.includes("Reference only · ERN is not treating this source as current."),"recheck viewer context must remain reference-only");
console.log("Atlas reference-only handoffs are explicit, actionable and truth-safe");
