import assert from "node:assert/strict";
import fs from "node:fs";
const root=new URL("../",import.meta.url);
const source=fs.readFileSync(new URL("src/atlas-marker-groups.js",root),"utf8");
const app=fs.readFileSync(new URL("src/app-lite.js",root),"utf8");
const index=fs.readFileSync(new URL("index.html",root),"utf8");
const sources=JSON.parse(fs.readFileSync(new URL("data/sources.json",root),"utf8"));
const held=sources.find(s=>s.id==="taiwan-heping-island-live");
assert.ok(held&&held.health==="DEGRADED"&&held.watchHold&&held.featuredHold);
assert.match(held.failureReason,/VISITOR_PLAYBACK_REJECTED/);
assert.match(source,/pin\.textContent=String\(group\.length\)/,"Numbered clusters must always show their count");
assert.match(source,/pin\.onclick=\(\)=>showMapGroup\(group,pin\)/,"Click opens a place list directly");
assert.match(source,/entry\.node\.click\(\)/,"List retains original source actions");
assert.match(source,/role","dialog"/,"Place list is a dialog");
assert.match(source,/aria-haspopup","dialog"/,"Cluster announces its list");
assert.match(source,/Escape/,"Escape closes a group");
assert.match(source,/entries=\[\.\.\.entries\]\.sort/,"Current sources appear first in large place lists");
for(const phrase of ["atlasZoomTransform","ZOOM_STYLES","ensureAtlasZoom","focusMapGroup","atlasView.scale","pointermove","wheel","World view"])assert.ok(!source.includes(phrase),"Removed unwanted map complexity: "+phrase);
assert.ok(!index.includes("atlas-zoom.js?v="),"No legacy second zoom controller");
assert.ok(app.includes('import("./atlas-marker-groups.js")'),"Simple groups still load on demand");
console.log("Simple numbered Living Atlas with scrollable source list and Heping hold passed");
