import assert from "node:assert/strict";
import {spawnSync} from "node:child_process";
const r=spawnSync(process.execPath,["scripts/autonomous-work-status.mjs"],{encoding:"utf8"});
assert.equal(r.status,0,r.stderr);
const x=JSON.parse(r.stdout);
assert.equal(x.coreComplete,true);
assert.ok(["CORE_COMPLETE_EXTERNAL_OPTIONAL","CORE_COMPLETE_PHASE_4_PILOT_ACTIVE"].includes(x.completionState));
assert.ok(["LOCAL_AUTONOMOUS_WORK_OPEN","EXTERNAL_REVIEW_ELIGIBLE","AUTONOMOUS_HOLD_EXTERNAL_WAIT"].includes(x.state));
assert.ok(Array.isArray(x.localBlockers));
assert.ok(Array.isArray(x.externalEligibleNow));
assert.ok(Array.isArray(x.persistentStaleDebt));
for(const k of ["inventWorkToAvoidHold","reopenCompletedLaneWithoutTrigger","automaticExternalActionAllowed","automaticPublicActivationAllowed","timePassingAloneCountsAsSuccess"])assert.equal(x.safety[k],false);
assert.match(x.note,/core is complete/i);
console.log("Canonical autonomous-work status preserves core completion and anti-loop safety");
