import assert from "node:assert/strict";import {pilotObservationStatus} from "../src/current-image-pilot-observation.js";
const base={activatedAt:"2026-10-05T07:20:00Z",requiredSuccessfulRenewalDates:2,allowedSourceIds:["a","b"],observations:[]};
let s=pilotObservationStatus(base,{now:new Date("2026-10-05T12:00:00Z")});assert.equal(s.expansionReady,false);assert.equal(s.state,"OBSERVING");assert.equal(s.renewalOverdue,false);assert.equal(s.nextExpectedScheduledAt,"2026-10-06T00:37:00.000Z");
s=pilotObservationStatus(base,{now:new Date("2026-10-06T03:00:00Z")});assert.equal(s.state,"RENEWAL_OVERDUE");assert.deepEqual(s.missingExpectedScheduledRenewalDates,["2026-10-06"]);assert.equal(s.expansionReady,false);
const obs=d=>({observedAt:d+"T00:37:00Z",utcDate:d,event:"schedule",state:"RENEWED",items:[{id:"a",evidenceAgeMinutes:5},{id:"b",evidenceAgeMinutes:6}]});
s=pilotObservationStatus({...base,observations:[obs("2026-10-06"),obs("2026-10-07")]},{now:new Date("2026-10-07T01:00:00Z")});
assert.equal(s.expansionReady,true);assert.equal(s.state,"OBSERVATION_REQUIREMENT_MET");assert.equal(s.safety.automaticExpansionAllowed,false);
s=pilotObservationStatus({...base,observations:[{...obs("2026-10-06"),event:"workflow_dispatch"},obs("2026-10-07")]},{now:new Date("2026-10-07T01:00:00Z")});
assert.equal(s.expansionReady,false);assert.equal(s.renewalOverdue,true);
console.log("Current-image pilot requires scheduled renewals, detects missed slots and remains editorial-only");
