import fs from "node:fs";import assert from "node:assert/strict";
const yml=fs.readFileSync(".github/workflows/current-image-pilot-renewal.yml","utf8");
const script=fs.readFileSync("scripts/renew-current-image-pilot.mjs","utf8");
assert.match(yml,/workflow_dispatch:/);
assert.match(yml,/cron:\s*"37 0 \* \* \*"/);
assert.doesNotMatch(yml,/\n\s*push:/);
assert.match(yml,/contents:\s*write/);
assert.match(yml,/cancel-in-progress:\s*false/);
assert.match(yml,/data\/current-image-pilot-observations\.json/);
assert.match(script,/yellowstone-biscuit-basin-current-image/);
assert.match(script,/nz-ruapehu-current-image/);
assert.equal((script.match(/current-image-pilot-observations\.json/g)||[]).length,1);
assert.match(script,/GITHUB_EVENT_NAME/);
assert.match(script,/PILOT_CONTRACT_MISMATCH/);
assert.match(script,/Pilot observation ledger schema mismatch/);
assert.match(script,/Pilot observation ledger identity mismatch/);
assert.match(script,/Pilot observation ledger renewal requirement mismatch/);
assert.match(script,/Pilot observation ledger allowed source ids mismatch/);
assert.match(script,/Pilot observation ledger observations must be an array/);
assert.match(script,/FETCH_OK_TEMPORAL_EVIDENCE_CURRENT/);
assert.match(script,/permissionMutationAllowed:false/);
assert.match(script,/playbackMutationAllowed:false/);
assert.match(script,/rankingMutationAllowed:false/);
console.log("Current-image pilot renewal workflow stays scheduled/manual-only, exactly two-source and fail-closed");
