import assert from "node:assert/strict";
import fs from "node:fs";
const builder=fs.readFileSync(new URL("../scripts/build-destination-pages.mjs",import.meta.url),"utf8");
assert.match(builder,/sourceAvailabilityState/,"destination pages must inspect source availability schedules");
assert.match(builder,/Outside published live hours/,"scheduled-closed sources need a truthful public section");
assert.match(builder,/embedPlaybackProofCurrent/,"inside-ERN embeds need fresh playback proof on destination pages");
assert.match(builder,/PLAYBACK RECHECK DUE/,"expired playback proof must not retain a live label");
assert.match(builder,/Playback checked/,"inside-ERN destination cards should expose playback proof date separately from source verification");
assert.match(builder,/const offers=currentItems\.length\?offerForPlace\(id\):\[\]/,"stale-only pages must not surface affiliate offers");
assert.match(builder,/currentTravelOffer/,"affiliate offers must pass current verification");
assert.match(builder,/activeAffiliatePartner/,"affiliate offers must require an active partner");
assert.match(builder,/Affiliate availability never affects ERN source ranking/,"affiliate ranking independence must be disclosed");
assert.match(builder,/These entries are not paid placements/,"reviewed local entries must remain explicitly non-paid");
assert.match(builder,/const indexable=currentItems\.length>0\|\|scheduledClosedItems\.length>0/,"stale-only destination pages must be noindex");
assert.match(builder,/indexable\?"index,follow":"noindex,follow"/,"destination robots state must follow current/scheduled evidence");
assert.match(builder,/if\(indexable\)urls\.push/,"noindex destination pages must stay out of the sitemap");
assert.match(builder,/const primaryCta=currentItems\.length/,"destination primary CTA must depend on current truth");
assert.match(builder,/Explore current ERN windows/,"non-current destination pages need current-alternative CTA");
assert.match(builder,/const structuredRows=placeRows\.filter\(p=>p\.indexable\)/,"structured place directory must exclude reference-only rows");
assert.match(builder,/Number\(b\.indexable\)-Number\(a\.indexable\)/,"place directory should list current/scheduled destinations before reference-only rows");
assert.match(builder,/placeIndexable\(rows\)/,"related destination links should exclude reference-only stale places");
console.log("Destination pages preserve schedule, playback, local-place and commercial truth boundaries");
