import assert from "node:assert/strict";import {earthSuggestions,suggestionForEmptyIntent} from "../src/earth-suggestions.js";
globalThis.localStorage={getItem:k=>k==="ern:recent-searches:v1"?JSON.stringify(["one","two","three","four"]):null,setItem:()=>{}};
const all=earthSuggestions({currentAvailable:true,limit:5,includeRecent:false});
assert.equal(all[0].label,"✨ What’s good on Earth right now?");
assert.ok(all.some(x=>x.intents.includes("snow")));
assert.ok(all.some(x=>x.intents.includes("golden")));
assert.ok(all.some(x=>x.query==="surprise me"));
const noCurrent=earthSuggestions({currentAvailable:false,limit:5,includeRecent:false});
assert.ok(noCurrent.every(x=>!x.current));
assert.ok(noCurrent.some(x=>x.intents.includes("snow")));
assert.equal(suggestionForEmptyIntent({currentAvailable:false,includeRecent:false})?.query,"where can I see snow");
const mixed=earthSuggestions({currentAvailable:true,limit:5});
assert.ok(mixed.filter(x=>x.recent).length<=2);
assert.equal(mixed[0].label,"✨ What’s good on Earth right now?");
console.log("ERN Guide starter balance checks passed");
