import fs from "node:fs";
const cfg=fs.readFileSync("signals-worker/wrangler.jsonc","utf8");
const worker=fs.readFileSync("signals-worker/src/index.js","utf8");
const state=fs.readFileSync("signals-worker/src/signal-state.js","utf8");
const workerModule=await import("../signals-worker/src/index.js");
const stateModule=await import("../signals-worker/src/signal-state.js");

console.assert(typeof workerModule.default?.fetch==="function","Earth Signals Worker module must export fetch");
console.assert(typeof stateModule.SignalState==="function","Earth Signals Worker must export SignalState");
console.assert(cfg.includes('"ERN_EARTH_SIGNALS_ENABLED": "false"')||cfg.includes('"ERN_EARTH_SIGNALS_ENABLED": "true"'),"Earth Signals runtime flag must be explicit");
console.assert(worker.includes('enabled=env.ERN_EARTH_SIGNALS_ENABLED==="true"')&&worker.includes('if(!enabled)return reply(503,{ok:false,mode:"READ_ONLY",reason:"EARTH_SIGNALS_NOT_ACTIVATED"}'),"Earth Signals Worker must fail closed unless runtime flag is explicitly true");
console.assert(cfg.includes('"class_name": "SignalState"')&&cfg.includes('"storage": "sqlite"'),"Earth Signals durable state must use SQLite");
console.assert(worker.includes("earthSignalHttpRequest"),"Worker must reuse the canonical Earth Signal HTTP contract");
console.assert(worker.includes("readJsonBodyBounded")&&worker.includes("4096"),"Earth Signal JSON bodies must be bounded even without Content-Length");
console.assert(worker.includes("ERN_RATE_HMAC_KEY")&&worker.includes("CF-Connecting-IP"),"Worker must derive rate subjects server-side");
console.assert(worker.includes("rawNetworkIdentifiersStored:false"),"Health response must state raw network identifiers are not stored");
console.assert(worker.includes("TRUSTED_CATALOG_UNAVAILABLE")&&worker.includes("ERN_CATALOG_URL"),"Worker must validate places from ERN's server-fetched catalog");
console.assert(worker.includes("SIGNAL_PLACE_ID_REQUIRED"),"Public Earth Signal listing must be place-scoped");
console.assert(worker.includes("constantTimeEqual")&&!worker.includes("got!==`Bearer ${expected}`"),"Earth Signal review bearer token must not use direct string equality");
console.assert(worker.indexOf("EARTH_SIGNALS_NOT_ACTIVATED")<worker.indexOf("const subject=await rateSubject"),"Worker must fail closed before rate-subject/catalog work when Signals are OFF");
console.assert(state.includes("CREATE TABLE IF NOT EXISTS signals")&&state.includes("CREATE TABLE IF NOT EXISTS reports"),"Durable signal/report storage missing");
console.assert(state.includes("CREATE TABLE IF NOT EXISTS rate_events"),"Durable subject-scoped rate state missing");
console.assert(state.includes("DELETE FROM signals WHERE expiry_at <= ?"),"Expiry cleanup must be implemented");
console.assert(state.includes("DUPLICATE_REPORT")&&state.includes("PLACE_LIMIT"),"Moderation rate boundaries missing");
console.log("earth-signal-worker deployable fail-closed foundation smoke: ok");
