import {EARTH_SIGNAL_MEDIA_POLICY,earthSignalMediaPublishable,earthSignalMediaPublicRecord} from "../src/earth-signal-media-policy.js";
console.assert(EARTH_SIGNAL_MEDIA_POLICY.photo.enabled===false);
console.assert(EARTH_SIGNAL_MEDIA_POLICY.video.enabled===false);
console.assert(EARTH_SIGNAL_MEDIA_POLICY.video.maxSeconds===15);
console.assert(EARTH_SIGNAL_MEDIA_POLICY.photo.stripMetadata===true);
const approved={kind:"photo",moderation:"APPROVED",storageExpiryAt:"2026-09-21T13:00:00Z",metadataStripped:true,placeId:"x",lat:1,lon:2,locationEvidence:"NEAR_PLACE"};
console.assert(!earthSignalMediaPublishable(approved),"media stays disabled until infrastructure activation");
const pub=earthSignalMediaPublicRecord(approved);
console.assert(!("lat" in pub)&&!("lon" in pub),"public media record must omit precise coordinates");
console.assert(pub.temporary&&pub.nearPlaceVerified);
console.log("Earth Signal media boundary checks passed");
