import assert from "node:assert/strict";import {earthGuidePreferenceAction,earthGuidePreferenceReply} from "../src/earth-guide-preference.js";
assert.equal(earthGuidePreferenceAction("Something less expensive?",{placeId:"z"}).type,"PRICE");
assert.equal(earthGuidePreferenceAction("Is there a quieter place?",{placeId:"z"}).type,"QUIET");
assert.equal(earthGuidePreferenceAction("Something less expensive?",{placeId:null}),null);
assert.equal(earthGuidePreferenceAction("Is there a quieter place?",{placeId:null}),null);
assert.equal(earthGuidePreferenceReply({type:"PRICE"},{placeTitle:"Zermatt"}).canAnswer,false);
assert.match(earthGuidePreferenceReply({type:"PRICE"},{placeTitle:"Zermatt"}).text,/Zermatt/);
assert.match(earthGuidePreferenceReply({type:"PRICE"},{placeTitle:"Zermatt"}).text,/won’t guess/);
assert.equal(earthGuidePreferenceReply({type:"QUIET"},{placeTitle:"Zermatt"}).canAnswer,false);
assert.equal(earthGuidePreferenceReply({type:"PRICE"},{hasVerifiedPriceData:true,placeTitle:"Zermatt"}).canAnswer,true);
assert.equal(earthGuidePreferenceAction("Show me now"),null);
console.log("ERN Guide preference truth checks passed");
