import fs from "node:fs";
import assert from "node:assert/strict";

const src=fs.readFileSync(new URL("../scripts/build-destination-pages.mjs",import.meta.url),"utf8");
assert.match(src,/about\.html/);
assert.match(src,/privacy\.html/);
assert.match(src,/staticUrls/);
assert.match(src,/places\/index\.html/);
assert.match(src,/BreadcrumbList/);
assert.match(src,/CollectionPage/);
assert.match(src,/ItemList/);
assert.match(src,/dateModified/);
assert.match(src,/base\+"places\/"/);
assert.match(src,/base\+"countries\/"/);
assert.match(src,/countryHubEligible/);
assert.match(src,/substantial country hubs/);
assert.match(src,/recentFeedRows/);
assert.match(src,/updates\\.xml/);
assert.match(src,/mainEntity/);
console.log("generated sitemap and destination hierarchy guard passed");
