import fs from "node:fs";import assert from "node:assert/strict";
const app=fs.readFileSync("src/app-lite.js","utf8");
assert.match(app,/function createMediaFrame/);
assert.match(app,/function heroLivePreviewAllowed/);
assert.match(app,/min-width:1000px/);
assert.match(app,/connection\?\.saveData===true/);
assert.match(app,/s\.playback==="EMBED"/);
assert.match(app,/currentTruthClaim\(s\)/);
assert.match(app,/cleanUrl\(s\.embedUrl\)/);
assert.match(app,/const frame=createMediaFrame\(s,\{preview:true/);
assert.match(app,/preview\?"fullscreen; picture-in-picture":"autoplay; fullscreen; picture-in-picture"/);
assert.match(app,/frame\.setAttribute\("aria-hidden","true"\)/);
assert.match(app,/mount\.dataset\.visualKind="live-preview"/);
assert.match(app,/onerror:\(\)=>/);
assert.equal((app.match(/createElement\(["']iframe["']\)/g)||[]).length,1);
new Function(app);
console.log("ERN Hero proven live-preview gate passed");
