import { navigationState,syncPlaceNavigation } from "../src/navigation-sync.js";
const places=[{id:"chiang-mai"},{id:"wil"}];
console.assert(navigationState({hash:"#place=wil",places}).placeId==="wil");
console.assert(!navigationState({hash:"#place=missing",places}).hasPlace);
let opened=null,closed=0;
console.assert(syncPlaceNavigation({hash:"#place=chiang-mai",places,openPlace:(id,opts)=>{opened={id,opts};return true},closePlace:()=>{closed++;return true}}));
console.assert(opened.id==="chiang-mai"&&opened.opts.writeHistory===false&&opened.opts.recordRecent===false,"history navigation must not create another history entry or recent visit");
syncPlaceNavigation({hash:"",places,openPlace:()=>false,closePlace:opts=>{closed++;console.assert(opts.writeHistory===false);return true}});
console.assert(closed===1,"clearing a place hash should close the drawer");
const registry=new Map([["cam",{id:"cam",placeId:"wil"}]]);let windowOpened=null;console.assert(syncPlaceNavigation({hash:"#window=cam&place=wil",places,registry,openPlace:()=>true,openWindow:(s,opts)=>{windowOpened={s,opts};return true},closePlace:()=>true}));console.assert(windowOpened.s.id==="cam"&&windowOpened.opts.surface==="shared-window","shared window deep link must restore exact source");
const windowOnly=navigationState({hash:"#window=cam",places,registry});console.assert(windowOnly.hasWindow&&!windowOnly.hasPlace&&windowOnly.placeMatchesSource,"window-only share must be restorable without destination hash");
windowOpened=null;console.assert(syncPlaceNavigation({hash:"#window=cam",places,registry,openWindow:(s,opts)=>{windowOpened={s,opts};return true},closePlace:()=>true}));console.assert(windowOpened.s.id==="cam","window-only startup link must open exact source");
let mismatchOpened=false,placeFallback=false;console.assert(syncPlaceNavigation({hash:"#window=cam&place=chiang-mai",places,registry,openPlace:id=>{placeFallback=id==="chiang-mai";return true},openWindow:()=>{mismatchOpened=true;return true},closePlace:()=>true}));console.assert(placeFallback&&!mismatchOpened,"mismatched window/place hash must not open a source under the wrong destination");
console.log("ERN navigation sync smoke checks passed");
