import fs from "node:fs";
const cfg=fs.readFileSync("media-worker/wrangler.jsonc","utf8");
const worker=fs.readFileSync("media-worker/src/index.js","utf8");
const state=fs.readFileSync("media-worker/src/media-state.js","utf8");
const wm=await import("../media-worker/src/index.js");
const sm=await import("../media-worker/src/media-state.js");

console.assert(typeof wm.default?.fetch==="function"&&typeof wm.default?.scheduled==="function","Media Worker must expose fetch + scheduled cleanup");
console.assert(typeof sm.MediaState==="function","MediaState export missing");
console.assert(cfg.includes('"ERN_NOW_MOMENT_PHOTO_ENABLED": "false"'),"Photo Worker must deploy OFF by default");
console.assert(cfg.includes('"binding": "NOW_MOMENT_MEDIA"')&&cfg.includes('"bucket_name": "ern-now-moment-media"'),"Private R2 binding missing");
console.assert(cfg.includes('"*/15 * * * *"'),"TTL cleanup cron missing");
console.assert(worker.includes("directBucketPublicAccess:false"),"Worker must state bucket is not public");
console.assert(worker.includes("automaticPublicationAllowed:false"),"Worker must prohibit automatic publication");
console.assert(worker.includes("ERN_MEDIA_REVIEW_TOKEN")&&worker.includes("ERN_MEDIA_RATE_HMAC_KEY"),"Media runtime secrets missing");
console.assert(worker.includes("constantTimeEqual")&&!worker.includes("got===`Bearer ${expected}`"),"Review bearer token should not use direct string equality");
console.assert(worker.includes("PENDING_REVIEW")&&worker.includes("published:false"),"Upload must remain moderation-first");
console.assert(worker.includes("PLACE_ID_REQUIRED"),"Public temporary-photo listing must be place-scoped");
console.assert(worker.includes("readBodyBounded")&&worker.includes("DERIVATIVE_TOO_LARGE"),"Worker must stream uploads through a hard stored-byte ceiling");
for(const h of ["x-ern-photo-source-bytes","x-ern-photo-stored-bytes","x-ern-photo-width","x-ern-photo-height"])console.assert(!worker.includes(h),"Worker must not trust client-declared image fact header "+h);
console.assert(worker.includes("mediaExtension")&&worker.includes('"webp"')&&worker.includes('"png"'),"Object keys must preserve normalized media type");
console.assert(worker.includes("publicEligible")&&worker.includes("published:enabled&&Boolean(result.public)"),"Review response must distinguish public eligibility from active publication");
console.assert(worker.includes("x-content-type-options")&&worker.includes("objectStore.get"),"Approved media proxy boundary missing");
console.assert(state.includes("MAX_RETAINED_MEDIA=500")&&state.includes("MEDIA_STORAGE_CAPACITY"),"Media storage capacity bound missing");
console.assert(state.includes("MAX_PHOTOS_PER_DAY=3")&&state.includes("MAX_PHOTOS_PER_PLACE_DAY=2"),"Photo rate bounds missing");
console.assert(state.includes('b.op==="list-expired"')&&state.includes('b.op==="delete"'),"Retry-safe expired media metadata contract missing");
console.assert(worker.includes('op:"list-expired"')&&worker.includes('op:"delete"'),"Worker adapter must preserve expired metadata until object deletion succeeds");
console.log("Phase L media Worker remains private, moderated, temporary and fail-closed");

console.assert((worker.match(/cache-control":"private, no-store"/g)||[]).length>=2,"Internal and approved public temporary media must remain non-cacheable");
console.assert(worker.includes("x-content-type-options")&&worker.includes("content-security-policy"),"Media responses need content-sniffing and active-content guards");
