import fs from "node:fs";import assert from "node:assert/strict";import {pagesDnsAssessment,domainNextAction,GITHUB_PAGES_A,GITHUB_PAGES_AAAA} from "../src/pages-domain-diagnostics.js";
const w=fs.readFileSync(".github/workflows/pages.yml","utf8"),s=fs.readFileSync("scripts/domain-health.mjs","utf8");
console.assert(w.includes("Diagnose custom-domain DNS and TLS"));console.assert(w.includes("npm run domain:health -- earthrightnow.app"));console.assert(w.includes("continue-on-error: true"));console.assert(w.includes("Publish custom-domain diagnostics"));console.assert(w.includes("Enforce custom-domain health"));console.assert(w.includes("The deployed artifact may be healthy; repair custom-domain DNS/HTTPS"));console.assert(w.includes("if: steps.domain.outcome == 'success'"));
assert.ok(s.includes('dns("CAA")'));assert.ok(s.includes("pagesDnsAssessment"));assert.ok(s.includes("domainNextAction"));
const good=pagesDnsAssessment({host:"earthrightnow.app",a:GITHUB_PAGES_A,aaaa:GITHUB_PAGES_AAAA,caa:[]});assert.equal(good.dnsState,"OK");assert.equal(good.a.matches,true);assert.equal(good.caa.allowsLetsEncrypt,true);
const badA=pagesDnsAssessment({host:"earthrightnow.app",a:["203.0.113.10"]});assert.equal(badA.dnsState,"APEX_A_MISMATCH");assert.ok(badA.recommended[0].includes("GitHub Pages"));
const bad6=pagesDnsAssessment({host:"earthrightnow.app",a:GITHUB_PAGES_A,aaaa:["2001:db8::1"]});assert.equal(bad6.dnsState,"APEX_AAAA_MISMATCH");
const caa=pagesDnsAssessment({host:"earthrightnow.app",a:GITHUB_PAGES_A,caa:['0 issue "example-ca.test"']});assert.equal(caa.dnsState,"CAA_BLOCKS_LETS_ENCRYPT");assert.equal(caa.caa.allowsLetsEncrypt,false);
const www=pagesDnsAssessment({host:"www.earthrightnow.app",cname:["jjcadenza5-arch.github.io."]});assert.equal(www.dnsState,"OK");assert.equal(www.cname.matches,true);
const badWww=pagesDnsAssessment({host:"www.earthrightnow.app",cname:["other.example"]});assert.equal(badWww.dnsState,"WWW_CNAME_MISMATCH");
assert.match(domainNextAction({state:"TLS_HOSTNAME_MISMATCH",dns:good}),/remove and re-add/i);
console.log("ERN Pages custom-domain diagnostics passed");
