import {spawnSync} from "node:child_process";
const r=spawnSync(process.execPath,["scripts/participation-infrastructure-status.mjs"],{encoding:"utf8"});
console.assert(r.status===0,"Participation infrastructure status must run");
const x=JSON.parse(r.stdout);
console.assert(["EARTH_SIGNALS_AND_SUBMISSIONS_DEPLOYED_MEDIA_PREPARED","EARTH_SIGNALS_RUNTIME_PILOT_STAGED_PUBLIC_OFF","EARTH_SIGNALS_LIMITED_PILOT_ACTIVE"].includes(x.state),"Participation status should recognize deployed infrastructure, staged runtime, or active limited pilot");
console.assert(x.phase4PilotActive===true,"Earth Signals limited Phase 4 pilot should be active");
console.assert(x.remainingPublicActivationOff===true,"Submission and Now Moment media must remain public-off");
console.assert(x.workers?.earthSignals?.deployed===true,"Earth Signals deployment evidence should be recognized");
console.assert(x.workers?.earthSignals?.publicEnabled===true,"Earth Signals limited public pilot should be active");
console.assert(x.workers?.earthSignals?.deploymentEvidence==="DEPLOYED","Earth Signals deployment evidence must be DEPLOYED");
console.assert(x.workers?.submissions?.deployed===true,"Submission deployment evidence should be recognized");
console.assert(x.workers?.submissions?.publicEnabled===false,"Submission public activation must remain off");
console.assert(x.workers?.submissions?.deploymentEvidence==="DEPLOYED","Submission deployment evidence must be DEPLOYED");
console.assert(/^https:\/\//.test(x.workers?.submissions?.endpointUrl||""),"Submission endpoint should be recorded");
console.assert(x.workers?.nowMomentMedia?.prepared===true,"Now Moment media Worker should be prepared");
console.assert(x.workers?.nowMomentMedia?.publicEnabled===false,"Now Moment media public activation must remain off");
console.assert(x.workers?.nowMomentMedia?.deploymentEvidence==="NOT_DEPLOYED","Now Moment media deployment evidence must remain NOT_DEPLOYED");
console.assert(x.safety?.automaticPublicActivationAllowed===false,"Automatic public activation must stay forbidden");
console.assert(x.safety?.pushTriggeredInfrastructureDeploymentAllowed===false,"Participation deployment must remain manual-only");
console.assert(x.next==="OBSERVE_EARTH_SIGNALS_LIMITED_PILOT","Next state should be controlled pilot observation");
console.log("participation infrastructure status recognizes active Earth Signals pilot while preserving remaining public-off boundaries");
