import "./test-browser-env.mjs";
import { performanceBudget,performanceSnapshot,performanceBudgetResult } from "../src/performance-budget.js";
const root=document.createElement("div"),budget=performanceBudget();
console.assert(budget.activeMediaMax===1,"ERN performance budget must preserve one-player architecture");
root.innerHTML='<iframe src="https://example.com/live"></iframe>';
let snap=performanceSnapshot({root,now:()=>1});
console.assert(snap.activeMedia===1&&snap.mediaElements===1);
console.assert(performanceBudgetResult(snap).ok);
root.innerHTML='<iframe src="https://example.com/a"></iframe><video src="https://example.com/b"></video>';
const bad=performanceBudgetResult(performanceSnapshot({root,now:()=>2}));
console.assert(!bad.ok&&bad.blockers.includes("MULTIPLE_ACTIVE_MEDIA"));
root.innerHTML='<iframe></iframe><video hidden src="https://example.com/b"></video>';
snap=performanceSnapshot({root,now:()=>3});
console.assert(snap.mediaElements===2&&snap.activeMedia===0,"inactive placeholders must not be counted as active players");
console.log("ERN performance budget smoke checks passed");
