import assert from "node:assert/strict";
import {execFileSync} from "node:child_process";
const report=JSON.parse(execFileSync(process.execPath,["scripts/phase6-discovery-qa.mjs"],{encoding:"utf8"}));
assert.equal(report.phase,6);
assert.equal(report.state,"PHASE6_COMPLETE_VERIFIED");
assert.equal(report.issueCount,0);
assert.equal(report.separateFeatureGatesRemainOff,true);
assert.equal(report.safety.automaticGateActivationAllowed,false);
assert.equal(report.next,"NO_PHASE6_WORK_REOPENED");
console.log("Phase 6 discovery and growth exit QA passed");
