import assert from "node:assert/strict";
import {spawnSync} from "node:child_process";
const r=spawnSync(process.execPath,["scripts/project-phase-status.mjs"],{encoding:"utf8"});
assert.equal(r.status,0,r.stderr);
const x=JSON.parse(r.stdout);
assert.equal(x.currentStage,"STAGE_R_EXTERNAL_GATE_TRIGGER_REGISTER");
assert.equal(x.phaseNumber,4);
assert.equal(x.phaseLabel,"Controlled Infrastructure Pilots");
assert.equal(x.phaseState,"ACTIVE_INFRASTRUCTURE_VERIFIED_PUBLIC_PILOT_OFF");
assert.equal(x.coreStableBeta,true);
assert.equal(x.coreComplete,true);
assert.equal(x.completionState,"CORE_COMPLETE_PHASE_4_ACTIVE");
assert.ok(Number.isInteger(x.openExternalGates)&&x.openExternalGates>=1);
assert.ok(Array.isArray(x.eligibleExternalGates));
assert.ok(Array.isArray(x.blockedExternalGates));
assert.ok(Object.prototype.hasOwnProperty.call(x,"nextTimedReview"));
assert.equal(x.eligibleExternalGates.length+x.blockedExternalGates.length,x.openExternalGates);
assert.match(x.interpretation,/Phase 3 is complete and Phase 4 is active/);
assert.equal(x.next,"EARTH_SIGNALS_LIMITED_PILOT_REQUIRES_EXPLICIT_ACTIVATION_DECISION");
assert.equal(x.safety.automaticExternalActionAllowed,false);
assert.equal(x.safety.automaticPublicActivationAllowed,false);
console.log("Canonical ERN phase advances to Phase 4 while keeping public activation explicit");
