import assert from "node:assert/strict";
import {spawnSync} from "node:child_process";
const r=spawnSync(process.execPath,["scripts/project-phase-status.mjs"],{encoding:"utf8"});
assert.equal(r.status,0,r.stderr);
const x=JSON.parse(r.stdout);
assert.equal(x.currentStage,"STAGE_R_EXTERNAL_GATE_TRIGGER_REGISTER");
assert.equal(x.phaseNumber,6);
assert.equal(x.phaseLabel,"Discovery & Growth");
assert.equal(x.phaseState,"ACTIVE_PHASE6_NON_GATED_DISCOVERY_GROWTH");
assert.equal(x.coreStableBeta,true);
assert.equal(x.coreComplete,true);
assert.equal(x.completionState,"CORE_COMPLETE_PHASE_6_ACTIVE");
assert.ok(Number.isInteger(x.openExternalGates)&&x.openExternalGates>=1);
assert.ok(Array.isArray(x.eligibleExternalGates));
assert.ok(Array.isArray(x.blockedExternalGates));
assert.ok(Object.prototype.hasOwnProperty.call(x,"nextTimedReview"));
assert.equal(x.eligibleExternalGates.length+x.blockedExternalGates.length,x.openExternalGates);
assert.match(x.interpretation,/Phase 6 Discovery & Growth is active/);
assert.equal(x.next,"CONTINUE_PHASE6_DISCOVERY_GROWTH");
assert.equal(x.safety.automaticExternalActionAllowed,false);
assert.equal(x.safety.automaticPublicActivationAllowed,false);
console.log("Canonical ERN phase tracks approved Phase 6 while separate lanes remain gated");
