import assert from "node:assert/strict";
import { operationsReport } from "../src/operations-report.js";
const now="2026-09-20T12:00:00Z";
const source={id:"cam-a",placeId:"p",title:"A",provider:"P",country:"T",truth:"LIVE_VIDEO",permission:"LINK_ONLY",health:"UNKNOWN",playback:"EXTERNAL",sourceUrl:"https://example.com/live",checkedAt:now};
let r=operationsReport([source],{checkedAt:now,providerObservations:[{id:"cam-a",httpStatus:200}]});
assert.equal(r.healthAutomation.providerInput.accepted,1);
assert.equal(r.healthAutomation.proposals,1);
assert.equal(r.healthAutomation.changes,0);assert.equal(r.healthAutomation.inconclusive,1);assert.equal(r.healthAutomation.confirmedHealthy,0);assert.deepEqual(r.healthAutomation.outcomeDetails.inconclusive,[{id:"cam-a",observedAt:now}]);
r=operationsReport([source],{checkedAt:now,providerObservations:[{id:"cam-a",httpStatus:200,confirmation:"MEDIA_ENDPOINT"}]});
assert.equal(r.healthAutomation.proposals,1);
assert.equal(r.healthAutomation.complete,true);assert.equal(r.healthAutomation.confirmedHealthy,1);assert.equal(r.healthAutomation.inconclusive,0);assert.deepEqual(r.healthAutomation.outcomeDetails.inconclusive,[]);
console.log("provider observations operations integration passed");
