import assert from "node:assert/strict";
import {assessCurrentImageProbe} from "../src/provider-current-image-verification.js";
const target={integrationKind:"PROVIDER_AUTHORIZED_CURRENT_IMAGE",exactTargetUrl:"https://example.com/current.jpg"};
const fresh=assessCurrentImageProbe(target,{image:{status:200,contentType:"image/jpeg",bytes:5000},metadata:{status:200,body:{properties:{timestamp:"2026-10-05T06:00:00Z"}}},now:new Date("2026-10-05T06:30:00Z")});
assert.equal(fresh.state,"FETCH_OK_METADATA_CURRENT");assert.equal(fresh.catalogMutationAllowed,false);
const noMeta=assessCurrentImageProbe(target,{image:{status:200,contentType:"image/jpeg",bytes:5000},now:new Date("2026-10-05T06:30:00Z")});
assert.equal(noMeta.state,"FETCH_OK_TEMPORAL_SAMPLE_REQUIRED");assert.equal(noMeta.automatedReviewPassed,true);
const bad=assessCurrentImageProbe(target,{image:{status:200,contentType:"text/html",bytes:5000}});
assert.equal(bad.state,"FETCH_OR_IMAGE_INVALID");
console.log("Current-image automated verification stays fail-closed");
