import assert from "node:assert/strict";
import fs from "node:fs";
import {providerConcentration} from "../src/provider-concentration.js";
const rows=JSON.parse(fs.readFileSync(new URL("../data/sources.json",import.meta.url),"utf8"));
const r=providerConcentration(rows);
assert.equal(r.total,rows.length);
assert.ok(r.total>=94,"catalog should not regress below the established baseline");
assert.ok(r.providerCount>20,"catalog should remain provider-diverse");
assert.ok(r.domainCount>20,"catalog should remain domain-diverse");
assert.ok(r.topProviderShare<.20,"largest provider should remain below advisory concentration threshold");
assert.ok(r.topDomainShare<.20,"largest source domain should remain below advisory concentration threshold");
assert.equal(rows.filter(x=>/couchtourist/i.test(String(x.provider||"")+" "+String(x.sourceUrl||"")+" "+String(x.officialUrl||""))).length,0);
console.log(`Provider/domain concentration healthy: ${r.topProvider} ${(r.topProviderShare*100).toFixed(1)}% · ${r.topDomain} ${(r.topDomainShare*100).toFixed(1)}%`);
