import assert from "node:assert/strict";
import { operationsReport } from "../src/operations-report.js";
const now="2026-09-20T12:00:00Z";
const source={id:"cam-a",placeId:"p",title:"A",provider:"P",country:"T",truth:"LIVE_VIDEO",permission:"LINK_ONLY",health:"UNKNOWN",playback:"EMBED",sourceUrl:"https://example.com/live",checkedAt:now};
let r=operationsReport([source],{checkedAt:now,providerObservations:[{id:"cam-a",httpStatus:200}]});
assert.equal(r.healthAutomation.providerInput.accepted,1);
assert.deepEqual(r.healthAutomation.providerInput.evidenceDebt,[]);
assert.equal(r.healthAutomation.proposals,1);
assert.equal(r.healthAutomation.changes,0);assert.equal(r.healthAutomation.inconclusive,1);assert.equal(r.healthAutomation.confirmedHealthy,0);assert.equal(r.healthAutomation.outcomeDetails.inconclusive.length,1);assert.equal(r.healthAutomation.outcomeDetails.inconclusive[0].id,"cam-a");assert.equal(r.revalidation.next[0].id,"cam-a");assert.match(r.revalidation.next[0].reason,/INCONCLUSIVE_MEDIA/);
r=operationsReport([source],{checkedAt:now,providerObservations:[{id:"cam-a",httpStatus:200,confirmation:"MEDIA_ENDPOINT"}]});
assert.equal(r.healthAutomation.proposals,1);
assert.equal(r.healthAutomation.complete,true);assert.equal(r.healthAutomation.confirmedHealthy,1);assert.equal(r.healthAutomation.inconclusive,0);assert.deepEqual(r.healthAutomation.outcomeDetails.inconclusive,[]);
console.log("provider observations operations integration passed");

const stale=operationsReport([source],{checkedAt:now,providerObservations:[{id:"cam-a",httpStatus:200,confirmation:"HUMAN_PLAYBACK",observedAt:"2026-09-19T11:59:59.000Z"}]});
assert.ok(stale.healthAutomation.providerInput.staleObservationIds.includes("cam-a"));
assert.equal(stale.healthAutomation.providerInput.evidenceDebt[0].id,"cam-a");
assert.equal(stale.healthAutomation.providerInput.evidenceDebt[0].reason,"STALE_EVIDENCE");
assert.equal(stale.healthAutomation.confirmedHealthy,0);
assert.ok(stale.healthAutomation.invalidObservations.some(x=>x.id==="cam-a"&&x.reason==="STALE_OBSERVATION"));
assert.equal(stale.healthAutomation.complete,false);
assert.ok(stale.healthAutomation.issues.includes("INVALID_OBSERVATIONS"));
console.log("stale provider observation expiry passed");

const external={...source,id:"external-a",playback:"EXTERNAL"};
const scoped=operationsReport([source,external],{checkedAt:now,providerObservations:[]});
assert.equal(scoped.healthAutomation.providerInput.evidenceDebt.length,1);
assert.equal(scoped.healthAutomation.providerInput.evidenceDebt[0].id,"cam-a");
console.log("provider evidence debt scope passed");

const degraded={...source,id:"degraded-a",health:"DEGRADED",checkedAt:"2026-09-19T00:00:00Z"};
const prioritized=operationsReport([source,degraded],{checkedAt:now,providerObservations:[]});
assert.equal(prioritized.healthAutomation.providerInput.evidenceDebt[0].id,"degraded-a");
assert.equal(prioritized.healthAutomation.providerInput.evidenceDebt[0].priority,100);
assert.equal(prioritized.healthAutomation.providerInput.evidenceDebtSummary.total,2);
assert.equal(prioritized.healthAutomation.providerInput.evidenceDebtSummary.degraded,1);
assert.equal(prioritized.healthAutomation.providerInput.evidenceDebt[0].action,"REPROVE_PLAYBACK");
assert.equal(prioritized.healthAutomation.providerInput.evidenceDebt[0].reason,"DEGRADED_WITHOUT_CURRENT_EVIDENCE");
assert.deepEqual(prioritized.healthAutomation.providerInput.evidenceDebt[0].requiredEvidence,["MEDIA_ENDPOINT","HUMAN_PLAYBACK"]);
console.log("provider evidence debt priority passed");
