import assert from "node:assert/strict";
import fs from "node:fs";
import {providerConcentration} from "../src/provider-concentration.js";
const rows=JSON.parse(fs.readFileSync(new URL("../data/sources.json",import.meta.url),"utf8"));
const r=providerConcentration(rows);
assert.equal(r.total,94);
assert.ok(r.providerCount>20,"catalog should remain provider-diverse");
assert.ok(r.topShare<.20,"largest provider should remain below advisory concentration threshold");
assert.equal(rows.filter(x=>/couchtourist/i.test(String(x.provider||"")+" "+String(x.sourceUrl||"")+" "+String(x.officialUrl||""))).length,0);
console.log(`Provider concentration healthy: ${r.topProvider} ${(r.topShare*100).toFixed(1)}%`);
