import { publicationInventory,inventoryPublicationWarnings } from "../src/publication-inventory.js";
const now=Date.parse("2026-09-19T12:00:00.000Z"),checkedAt="2026-09-19T12:00:00.000Z";
const inside={id:"inside",health:"HEALTHY",permission:"EMBED_ALLOWED",playback:"EMBED",truth:"LIVE_VIDEO",sourceUrl:"https://example.test",embedUrl:"https://www.youtube.com/embed/ern-test",checkedAt,lastSuccessfulCheck:checkedAt};
const external={id:"external",health:"HEALTHY",permission:"LINK_ONLY",playback:"EXTERNAL",truth:"EXTERNAL_LIVE",sourceUrl:"https://example.test/live",checkedAt,lastSuccessfulCheck:checkedAt};
const stale={...external,id:"stale",checkedAt:"2026-09-10T00:00:00.000Z",lastSuccessfulCheck:"2026-09-10T00:00:00.000Z"};
const x=publicationInventory([inside,external,stale],{now});
console.assert(x.current===2&&x.insideERN===1&&x.externalCurrent===1,"inventory must distinguish current inside-ERN and external sources");
console.assert(x.currentIds.includes("inside")&&x.currentIds.includes("external"));
console.assert(x.recheckIds.includes("stale"));
console.assert(inventoryPublicationWarnings([inside,external],{now}).ok===true);
console.log("ERN publication inventory smoke checks passed");
