import { buildReleaseCandidate,releaseCandidateText } from "../src/release-candidate.js";
const now="2026-09-19T12:00:00.000Z",base={id:"inside",placeId:"p",title:"Inside",truth:"LIVE_VIDEO",permission:"EMBED_ALLOWED",health:"HEALTHY",playback:"EMBED",sourceUrl:"https://example.test",embedUrl:"https://example.test/embed",checkedAt:now,lastSuccessfulCheck:now};
const evidence=Object.fromEntries(["browser","mobile","providerPlayback","accessibility","performance","rollback"].map(key=>[key,{ok:true,note:key+" checked",checkedAt:now}]));
const c=buildReleaseCandidate([base],evidence,{now:Date.parse(now)});
console.assert(c.releasable===true,`fully current catalog plus fresh evidence should form a releasable candidate: ${JSON.stringify(c)}`);
console.assert(c.inventory.insideERN===1&&c.recheckIds.length===0);\nconsole.assert(c.inventory.currentIds.includes("inside"),"candidate inventory must use the same audit clock as release evidence");
console.assert(releaseCandidateText(c).includes("READY"));
const blocked=buildReleaseCandidate([base],{},{now:Date.parse(now)});
console.assert(!blocked.releasable&&blocked.publication.remaining.length===6,"missing real-world evidence must block candidate");
console.log("ERN release candidate smoke checks passed");
