import {readFileSync} from "node:fs";
const app=readFileSync(new URL("../src/app-lite.js",import.meta.url),"utf8");
const index=readFileSync(new URL("../index.html",import.meta.url),"utf8");
console.assert(app.includes('function recentSearches(){')&&app.includes('.slice(0,8):[]}'),"return-visitor search history should retain up to eight searches");
console.assert(app.includes('const recents=recentSearches().slice(0,2)'),"quick-search UI should preserve fresh discovery space");
console.assert(app.includes('rememberSearch(raw);renderQuickSearches()'),"explicit searches should refresh quick-return chips");
console.assert(app.includes('affinity=s=>baseScore(s)+8*')&&app.includes('p.categories?.[c]'),"Continue exploring should use browser-local country/category affinity");
console.assert(app.includes('writeSaved("ern:recent-searches:v1","[]")')&&app.includes('renderQuickSearches();renderWatch();renderWander();renderSaved();'),"Reset local suggestions should clear search re-entry memory");
console.assert(index.includes('./src/app-lite.js?v=20261007b'),"home should request the return-visitor app revision");
console.log("ERN return-visitor re-entry checks passed");
