import assert from "node:assert/strict";
import {readFileSync} from "node:fs";
const app=readFileSync(new URL("../src/app-lite.js",import.meta.url),"utf8");
const css=readFileSync(new URL("../src/styles-lite.css",import.meta.url),"utf8");
const start=app.indexOf("function renderMap(){"),end=app.indexOf("function renderMapStable()",start);
const map=app.slice(start,end);
assert.ok(start>0&&end>start);
assert.match(map,/const markers=\[\]/,"Map must retain all source markers before visual grouping");
assert.match(map,/for\(const marker of markers\)/,"Map must group existing mapped entries, not silently delete them");
assert.match(map,/for\(const entry of entries\)/,"Each map group must list all destinations");
assert.match(map,/entry\.node\.click\(\)/,"All grouped destinations must remain actionable");
assert.match(map,/aria-haspopup/,"Grouped markers must disclose their interactive drawer");
assert.match(map,/Escape/,"Map groups must be dismissible by keyboard");
assert.match(css,/\.map-pin\.cluster\{/,"Cluster count styling must be present");
assert.match(css,/\.map-cluster-panel\{/,"Grouped places need visible, scrollable drawer");
const preview=app.slice(app.indexOf("function watchPosterUrl("),app.indexOf("function createMediaFrame(",app.indexOf("function watchPosterUrl(")));
assert.match(preview,/s\?\.truth!=="LIVE_VIDEO"\|\|s\?\.playback!=="EMBED"\|\|s\?\.permission!=="EMBED_ALLOWED"/);
assert.match(preview,/https:\/\/i\.ytimg\.com\/vi\//);
assert.match(preview,/watch-card-play/);
assert.match(css,/VIDEO POSTER · NOT LIVE/);
assert.match(app,/function openViewer\(s,/,"Camera playback must remain click-driven in the shared viewer");
console.log("ERN screenshot-driven Watch poster truth + grouped map accessibility passed");
