import assert from "node:assert/strict";
import registry from "../data/seoul-context-place-mappings.json" with {type:"json"};
import {seoulContextMappingForPlace,seoulMappingValidationTarget} from "../src/seoul-context-mapping.js";
const target=seoulMappingValidationTarget(registry,"seoul-plaza");
assert.equal(target.ok,true);
assert.equal(target.areaName,"Gwanghwamun·Deoksugung");
assert.equal(target.realResponseValidated,false);
const publicMap=seoulContextMappingForPlace(registry,"seoul-plaza");
assert.equal(publicMap.ok,false);
assert.equal(publicMap.reason,"PLACE_MAPPING_REGISTRY_PUBLIC_OFF");
const approvedButRegistryOff={...registry,mappings:registry.mappings.map(x=>({...x,state:"APPROVED_VALIDATED",realResponseValidated:true,mayPublishContext:true}))};
assert.equal(seoulContextMappingForPlace(approvedButRegistryOff,"seoul-plaza").reason,"PLACE_MAPPING_REGISTRY_PUBLIC_OFF");
assert.equal(seoulContextMappingForPlace({...registry,publicActivationAllowed:true},"missing-place").reason,"PLACE_MAPPING_NOT_FOUND");
console.log("Seoul context mappings remain explicit, validation-only and public-OFF");
