import assert from "node:assert/strict";
import fs from "node:fs";
import {spawnSync} from "node:child_process";
const script=fs.readFileSync(new URL("../scripts/source-research-priority-status.mjs",import.meta.url),"utf8");
assert.match(script,/persistentStaleDebt/);
assert.match(script,/routineRecencyQueue/);
assert.match(script,/declared stale debt entry is current and should be reconciled/);
assert.doesNotMatch(script,/declared stale debt ids do not match catalog STALE_CHECK ids/);
const r=spawnSync(process.execPath,["scripts/source-research-priority-status.mjs"],{encoding:"utf8"});
assert.equal(r.status,0,r.stderr||r.stdout);
const out=JSON.parse(r.stdout);
assert.equal(out.ok,true);
assert.ok(Array.isArray(out.persistentStaleDebt));
assert.ok(Array.isArray(out.routineRecencyQueue));
console.log("Persistent stale research debt stays distinct from routine recency maintenance");
