import {telemetryEnvelope,telemetryPolicy} from "../src/telemetry-policy.js";
const p=telemetryPolicy();console.assert(p.defaultEnabled===false&&p.forbidden.includes("precise location")&&p.forbidden.includes("raw IP storage"));
console.assert(telemetryEnvelope("unknown",{email:"x@y.test"})===null,"unknown events must fail closed");
const x=telemetryEnvelope("earth_search",{length:42,query:"Chiang   Mai",contact:"x@y.test"});
console.assert(x.data.length===42&&x.data.query==="chiang mai"&&!Object.hasOwn(x.data,"contact"),"approved searches should be normalized while contact data remains excluded");
const sensitive=telemetryEnvelope("earth_search_zero",{query:"person@example.com",resultCount:0});
console.assert(!Object.hasOwn(sensitive.data,"query")&&sensitive.data.resultCount===0,"email-like searches must not be stored");
const y=telemetryEnvelope("window_opened",{sourceId:"cam",placeId:"p",lat:18.7,lon:98.9});
console.assert(y.data.sourceId==="cam"&&!Object.hasOwn(y.data,"lat")&&!Object.hasOwn(y.data,"lon"),"precise coordinates must not enter telemetry");
console.log("ERN telemetry privacy smoke checks passed");
