import assert from "node:assert/strict";
await import("../src/travel-planning-client.js");
const TP=globalThis.ERNTravelPlanning;
const now=Date.parse("2026-09-29T09:00:00Z");
const source={placeId:"place",health:"HEALTHY",truth:"LIVE_VIDEO"};
const partner={id:"partner-1",enabled:true,affiliate:true,verifiedAt:"2026-09-28T09:00:00Z",expiresAt:"2026-12-31T00:00:00Z"};
const base={id:"a",title:"A",provider:"P",partnerId:"partner-1",placeId:"place",intent:"activities",url:"https://example.test/",verified:true,verifiedAt:"2026-09-28T09:00:00Z"};
assert.equal(TP.current(base,now),true);
assert.equal(TP.current({...base,expiresAt:"2026-09-29T08:59:00Z"},now),false);
assert.equal(TP.current({...base,url:"http://example.test/"},now),false);
assert.equal(TP.partnerCurrent(partner,now),true);
assert.equal(TP.partnerCurrent({...partner,enabled:false},now),false);
assert.equal(TP.sourceEligible(source),true);
assert.equal(TP.sourceEligible({...source,health:"DEGRADED"}),false);
const offers=[base,{...base,id:"b",intent:"transport",verifiedAt:"2026-09-28T10:00:00Z"}];
assert.equal(TP.offerFor(offers,source,"transport",[partner],now).id,"b");
assert.equal(TP.offerFor(offers,source,"transport",[],now),null);
assert.equal(TP.offerFor(offers,{...source,truth:"REFERENCE"},"transport",[partner],now),null);
assert.equal(TP.offerFor(offers,source,"transport",[{...partner,enabled:false}],now),null);
assert.deepEqual(TP.guideOffers(offers,source,[partner],now).map(x=>x.id),["a","b"]);
assert.equal(TP.disclosure({...base,affiliate:true}),"Affiliate link");
console.log("Travel planning client keeps offer, active-partner, source-currentness and disclosure boundaries");
