import "./test-browser-env.mjs";
import { travelBridgeView,travelIntentMessage } from "../src/travel-bridge-view.js";
const place={id:"cm",title:"Chiang Mai",region:"Chiang Mai",country:"Thailand",lat:18.7,lon:98.9};
let seen=null;const view=travelBridgeView(place,{onIntent:(intent,ctx)=>seen={intent,ctx}});
console.assert(!view.hidden&&view.querySelectorAll("button").length===4,"ready destination should expose four planning intents");
view.querySelector("button").click();
console.assert(seen.intent==="stay"&&seen.ctx.placeId==="cm","travel intent must preserve destination context");
console.assert(travelIntentMessage("stay",place).includes("not connected yet"),"unconnected travel intent must be explicit");
const hidden=travelBridgeView({id:"x",title:"X"});
console.assert(hidden.hidden,"incomplete destination context must hide travel bridge");
console.log("ERN travel bridge view smoke checks passed");
