import fs from "node:fs";import assert from "node:assert/strict";
const worker=fs.readFileSync("travel-worker/src/index.js","utf8");
const manifest=JSON.parse(fs.readFileSync("data/viator-api-deployment.json","utf8"));
const map=JSON.parse(fs.readFileSync("data/viator-destination-map.json","utf8"));
const release=fs.readFileSync("scripts/build-release-snapshot.mjs","utf8");
const page=fs.readFileSync("release-verification.html","utf8");
assert.match(worker,/\/api\/viator\/destinations/);
assert.match(worker,/parentDestinationId/);
assert.match(worker,/lookupId/);
assert.equal(manifest.status,"DEPLOYED_AUTH_CONFIRMED_PUBLIC_OFF");
assert.equal(manifest.secretIsolation,true);
assert.equal(manifest.apiKeyConfigured,true);
assert.equal(manifest.taxonomyVerified,true);
assert.equal(manifest.productSearchVerified,false);
assert.equal(manifest.affiliateAttributionVerified,false);
assert.equal(manifest.publicActivationAllowed,false);
const auckland=map.mappings.find(x=>x.ernPlaceId==="auckland-viaduct-harbour");
assert.equal(auckland?.status,"APPROVED");
assert.equal(auckland?.viatorDestinationId,"391");
assert.equal(auckland?.countryEvidence?.countryMatch,true);
assert.match(release,/viator-api-deployment\.json/);
assert.match(release,/viator-destination-map\.json/);
assert.doesNotMatch(page,/Run one AI test|Find official Auckland destination|Diagnose Viator access/,"public static operator page must not expose quota-bearing API actions");
console.log("Viator taxonomy/operator boundary: auth+taxonomy confirmed, product/public activation still OFF");
