import fs from "node:fs";
import assert from "node:assert/strict";
const app=fs.readFileSync("src/app-lite.js","utf8");
assert.match(app,/s\?\.querySelector\("iframe,img,video"\)/);
assert.match(app,/state\.journeyTimer\?s:m\|\|s/);
assert.match(app,/\?\.requestFullscreen/);
assert.match(app,/\?\.webkitRequestFullscreen/);
assert.match(app,/\?\.webkitEnterFullscreen/);
assert.match(app,/classList\.add\("faux-fullscreen"\)/);
console.log("ERN viewer media-first fullscreen fallback passed");
