import assert from "node:assert/strict";
import fs from "node:fs";
import {premiumVisualEligible} from "../src/watch-earth-visual-gate.js";
import {buildWatchEarth,watchEarthEligible} from "../src/watch-earth.js";
const sources=JSON.parse(fs.readFileSync(new URL("../data/sources.json",import.meta.url),"utf8"));
const now=new Date("2026-10-09T10:47:00Z");
const base={quality:95,moment:94,timeZone:"Asia/Taipei",categories:["Cities & Streets"]};
assert.equal(premiumVisualEligible(base,{now}),true,"Strong scenes may qualify at day or night");
assert.equal(premiumVisualEligible({...base,quality:83},{now}),false);
assert.equal(premiumVisualEligible({...base,moment:79},{now}),false);
assert.equal(premiumVisualEligible({...base,watchHold:true},{now}),false);
assert.equal(premiumVisualEligible({...base,featuredHold:true},{now}),false);
const visible=buildWatchEarth(sources,{now,limit:5});
assert.ok(visible.length<=5,"Five is a ceiling");
assert.ok(visible.every(s=>watchEarthEligible(s,{now})&&premiumVisualEligible(s,{now})));
for(const id of ["verbier","taiwan-heping-island-live"])
 assert.ok(!visible.some(s=>s.id===id),id+" must not feature while explicitly held");
const verbier=sources.find(s=>s.id==="verbier");
assert.equal(verbier.health,"HEALTHY","A merely gray live camera must not be falsely called broken");
assert.equal(verbier.watchHold,true);
assert.match(verbier.watchVisualReason,/featureless gray/);
const app=fs.readFileSync(new URL("../src/app-lite.js",import.meta.url),"utf8");
assert.match(app,/function premiumVisual\(s\)\{return!!\(s&&s\.watchHold!==true&&s\.featuredHold!==true&&\+s\.quality>=84&&\+s\.moment>=80\)\}/);
assert.doesNotMatch(app,/premiumVisual\(s\).*h>=8&&h<17/);
assert.match(app,/&&premiumVisual\(s\)}/);
assert.match(app,/const elite=sorted;/,"Rotation searches the whole qualified premium pool for geographic diversity");
assert.match(app,/const offset=Math\.floor\(Date\.now\(\)\/3600000\)\+\(state\.setOffset\|\|0\)/,"Watch Earth rotates hourly");
assert.doesNotMatch(app.slice(app.indexOf("function buildWatch("),app.indexOf("function generatedBackground(")),/affiliate|commission|sponsored/i);
console.log("Watch Earth: beauty/interest without daylight lock, explicit holds, broad rotation and five-stream ceiling passed");
