import assert from "node:assert/strict";
import fs from "node:fs";
import {premiumVisualEligible} from "../src/watch-earth-visual-gate.js";
import {buildWatchEarth,watchEarthEligible} from "../src/watch-earth.js";
const sources=JSON.parse(fs.readFileSync(new URL("../data/sources.json",import.meta.url),"utf8"));
const day=new Date("2026-10-09T03:47:00Z");
const night=new Date("2026-10-09T17:47:00Z");
const base={quality:95,moment:94,timeZone:"Asia/Taipei",categories:["Cities & Streets"]};
assert.equal(premiumVisualEligible(base,{now:day}),true);
assert.equal(premiumVisualEligible(base,{now:night}),false,"Metadata/city alone cannot prove an attractive night view");
assert.equal(premiumVisualEligible({...base,quality:83},{now:day}),false);
assert.equal(premiumVisualEligible({...base,moment:79},{now:day}),false);
assert.equal(premiumVisualEligible({...base,watchHold:true},{now:day}),false);
const approval={...base,nightVisualReview:"VISUALLY_COMPELLING",nightVisualEvidence:"Positive human review of bright illuminated city lights",nightVisualVerifiedAt:night.toISOString()};
assert.equal(premiumVisualEligible(approval,{now:night}),true,"Source-specific recent positive night proof may qualify");
assert.equal(premiumVisualEligible({...approval,nightVisualEvidence:""},{now:night}),false);
assert.equal(premiumVisualEligible({...approval,nightVisualVerifiedAt:"2026-10-04T17:47:00Z"},{now:night}),false,"Old night-light proof expires");
const visible=buildWatchEarth(sources,{now:day,limit:5});
assert.ok(visible.length<=5&&visible.length>=2,"Hard quality ceiling, not forced quota");
assert.ok(visible.every(s=>watchEarthEligible(s,{now:day})&&premiumVisualEligible(s,{now:day})));
for(const id of ["verbier","taiwan-heping-island-live","la-palma-caldera-taburiente"])
 assert.ok(!visible.some(s=>s.id===id),id+" must not feature while gray, rejected or pre-dawn");
const verbier=sources.find(s=>s.id==="verbier");
assert.equal(verbier.health,"HEALTHY","A merely gray live camera must not be falsely called broken");
assert.equal(verbier.watchHold,true);
assert.match(verbier.watchVisualReason,/featureless gray/);
const app=fs.readFileSync(new URL("../src/app-lite.js",import.meta.url),"utf8");
assert.match(app,/function premiumVisual\(s\)/,"Browser must enforce a visual gate");
assert.match(app,/h>=8&&h<17/);
assert.match(app,/s.nightVisualReview==="VISUALLY_COMPELLING"/);
assert.match(app,/&&premiumVisual\(s\)}/);
assert.match(app,/const elite=sorted.slice\(0,7\)/,"Rotation must stay within a bounded upper tier");
assert.doesNotMatch(app.slice(app.indexOf("function buildWatch("),app.indexOf("function generatedBackground(")),/affiliate|commission|sponsored/i);
console.log("Premium Watch Earth: honest day/night scene gate, visual holds, bounded rotation and underfilled set passed");
