import fs from "node:fs";import assert from "node:assert/strict";
const targets=JSON.parse(fs.readFileSync("data/provider-generated-targets.json","utf8"));
const sources=JSON.parse(fs.readFileSync("data/sources.json","utf8"));
const t=targets.find(x=>x.id==="north-coast-yehliu-youtube-player");
assert.ok(t);
assert.equal(t.integrationKind,"PROVIDER_GENERATED_WIDGET");
assert.equal(t.truthIfApproved,"LIVE_VIDEO");
assert.equal(t.exactTargetUrl,"https://www.youtube.com/embed/ZjuY4qKaj40");
assert.equal(t.promotionAllowed,false);
assert.equal(t.catalogMutationAllowed,false);
assert.equal(t.automaticGenerationAllowed,false);
assert.equal(t.reviewedAt,"2026-10-05T10:05:03.929Z");
assert.equal(t.reviewOutcome,"HUMAN_PLAYBACK_CONFIRMED");
assert.equal(t.reviewEvidencePath,"data/review-evidence/yehliu-generated-2026-10-05.json");
const s=sources.find(x=>x.id===t.sourceId);
assert.ok(s);
assert.equal(s.permission,"LINK_ONLY");
assert.equal(s.playback,"EXTERNAL");
assert.equal(s.truth,"LIVE_IMAGE");
console.log("Yehliu exact YouTube player stays branded, human-confirmed, editorial-pending and non-promotional");
