import { loadRegistry, rankedSources, createERNPlayback } from "./source-registry.js";import { renderPlayback } from "./playback-adapters.js";
const $=s=>document.querySelector(s);const registry=await loadRegistry();let cleanup=null;let favorites=new Set(JSON.parse(localStorage.getItem("ern:favorites")||"[]"));
const usable=s=>s.id!=="recovery-placeholder";const all=rankedSources(registry,usable);let current=all[0]||null;
const player=createERNPlayback(registry,state=>{if(!state.open)return;const s=state.source;$("#viewer").hidden=false;$("#viewerTitle").textContent=s.title;$("#viewerStory").textContent=s.story||"";$("#viewerTruth").textContent=state.mode==="UNAVAILABLE"?"CHECKING SOURCE":s.truth.replaceAll("_"," ");$("#sourceViewer").href=s.sourceUrl;$("#favoriteViewer").textContent=favorites.has(s.id)?"♥":"♡";if(cleanup)cleanup();cleanup=renderPlayback(state.mode,s,$("#viewerMount"))||null;});
function truthLabel(s){if(s.health==="UNKNOWN")return "SOURCE CHECK";return s.truth.replaceAll("_"," ")}
function card(s){const d=document.createElement("article");d.className="card";d.innerHTML=`<div><span class="meta">${truthLabel(s)} · ${s.country}</span><h3>${s.title}</h3><p>${s.story||""}</p></div><div class="card-actions"><button data-play>Open window</button><button data-fav>${favorites.has(s.id)?"♥":"♡"}</button></div>`;d.querySelector("[data-play]").onclick=()=>player.play(s.id,{surface:"immersive"});d.querySelector("[data-fav]").onclick=()=>toggleFavorite(s.id);return d}
function renderInto(el,items){el.replaceChildren(...items.map(card))}
function setHero(s){if(!s)return;current=s;$("#heroTitle").textContent=s.title;$("#heroMeta").textContent=`${s.region||s.country} · ${s.story||""}`;$("#heroTruth").textContent=truthLabel(s)}
function toggleFavorite(id){favorites.has(id)?favorites.delete(id):favorites.add(id);localStorage.setItem("ern:favorites",JSON.stringify([...favorites]));renderFavorites();renderWindows()}
function renderWindows(){renderInto($("#windowRow"),all.slice(0,8))}
function renderFavorites(){renderInto($("#favoriteResults"),all.filter(s=>favorites.has(s.id)))}
const families=["All","Beautiful Earth","Interesting Earth","Useful Earth","Earth Happening Now","Wildlife","Beaches & Water","Cities & Streets","Volcanoes & Earth"];function renderFilters(){const box=$("#filters");box.replaceChildren(...families.map(name=>{const b=document.createElement("button");b.textContent=name;b.onclick=()=>renderInto($("#exploreResults"),name==="All"?all:all.filter(s=>s.categories?.includes(name)));return b}))}
function nextHero(){if(!all.length)return;setHero(all[(all.indexOf(current)+1)%all.length])}
document.querySelector('[data-action="watch-live"]').onclick=()=>current&&player.play(current.id,{surface:"immersive"});document.querySelector('[data-action="watch-earth"]').onclick=()=>all[0]&&player.play(all[0].id,{surface:"watch-earth"});document.querySelector('[data-action="my-earth"]').onclick=()=>$("#my-earth").scrollIntoView({behavior:"smooth"});document.querySelector('[data-action="explore"]').onclick=()=>$("#explore").scrollIntoView({behavior:"smooth"});document.querySelector('[data-action="next-live"]').onclick=nextHero;
$("#closeViewer").onclick=()=>{if(cleanup)cleanup();cleanup=null;player.close();$("#viewer").hidden=true;$("#viewerMount").replaceChildren()};$("#previousViewer").onclick=()=>player.previous();$("#nextViewer").onclick=()=>{const n=player.next();if(!n&&all.length){const i=Math.max(0,all.findIndex(s=>s.id===player.state.sourceId));player.play(all[(i+1)%all.length].id,{surface:player.state.surface})}};$("#fullViewer").onclick=()=>$("#viewer").requestFullscreen?.();$("#favoriteViewer").onclick=()=>player.state.sourceId&&toggleFavorite(player.state.sourceId);
$("#atlasSearch").oninput=e=>{const q=e.target.value.toLowerCase().trim();renderInto($("#atlasResults"),all.filter(s=>!q||[s.title,s.country,s.region,...(s.categories||[])].join(" ").toLowerCase().includes(q)))};
document.addEventListener("keydown",e=>{if($("#viewer").hidden)return;if(e.key==="Escape")$("#closeViewer").click();if(e.key==="ArrowRight")$("#nextViewer").click();if(e.key==="ArrowLeft")$("#previousViewer").click()});
setHero(current);renderWindows();renderFilters();renderInto($("#exploreResults"),all);renderInto($("#momentResults"),all.filter(s=>s.categories?.some(c=>["Beautiful Earth","Interesting Earth","Useful Earth","Earth Happening Now"].includes(c))));renderFavorites();renderInto($("#atlasResults"),all);
